"""create initial database schema

Revision ID: bfc7a4ba29c3
Revises: 
Create Date: 2026-10-03 17:47:45.076310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc7a4ba29c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_category_id'), 'complaints', ['category_id'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_complaint_id'), 'assignments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_assignments_staff_id'), 'assignments', ['staff_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_complaint_id'), 'notifications', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read_status'), 'notifications', ['read_status'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('resolution_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('resolver_id', sa.UUID(), nullable=False),
    sa.Column('resolution_details', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolver_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('resolution_id')
    )
    op.create_index(op.f('ix_resolutions_complaint_id'), 'resolutions', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_resolutions_resolver_id'), 'resolutions', ['resolver_id'], unique=False)
    op.create_table('sla',
    sa.Column('sla_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sla_id')
    )
    op.create_index(op.f('ix_sla_complaint_id'), 'sla', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_sla_deadline'), 'sla', ['deadline'], unique=False)
    op.create_index(op.f('ix_sla_escalation_level'), 'sla', ['escalation_level'], unique=False)
    op.create_table('status_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_status_history_changed_at'), 'status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_status_history_changed_by'), 'status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_status_history_complaint_id'), 'status_history', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_complaint_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_by'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_at'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_sla_escalation_level'), table_name='sla')
    op.drop_index(op.f('ix_sla_deadline'), table_name='sla')
    op.drop_index(op.f('ix_sla_complaint_id'), table_name='sla')
    op.drop_table('sla')
    op.drop_index(op.f('ix_resolutions_resolver_id'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_complaint_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_complaint_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_assignments_staff_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_complaint_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
